-- Add generated_image_url column to messages table
-- This stores the URL of images generated by AI (text-to-image feature)

ALTER TABLE messages ADD COLUMN IF NOT EXISTS generated_image_url TEXT;

-- Add index for faster queries on generated images
CREATE INDEX IF NOT EXISTS idx_messages_generated_image ON messages(generated_image_url) WHERE generated_image_url IS NOT NULL;
